# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create a redis aggregate queue.
#' 
#' @param ip The host address of the redis server.
#' @param port The port the redis server is listening on.
#' @return An external pointer to an instance of type RedisAggregateQueue.
#' @export
makeRAQ <- function(ip, port) {
    .Call('cnidaria_makeRAQ', PACKAGE = 'cnidaria', ip, port)
}

#' Add a resource queue to listen on.
#'
#' @param raq The pointer to the RedisAggregateQueue
#' @param key The key of the list to listen on
#' @return TRUE if the operation was successful FALSE otherwise
#' @export
addPop <- function(raq, key) {
    .Call('cnidaria_addPop', PACKAGE = 'cnidaria', raq, key)
}

#' Get the keys for the lists that the redis aggregate queue is listening on
#'
#' @param raq The redis aggregate queue
#' @return The keys corresponding to the redis lists that the raq is listening
#' on
#' @export
popKeys <- function(raq) {
    .Call('cnidaria_popKeys', PACKAGE = 'cnidaria', raq)
}

#' Remove a key from the listening key list
#' 
#' @param raq The redis aggregate queue
#' @param key The key to remove
#' @return TRUE if the 
#' @export
remPop <- function(raq, key) {
    .Call('cnidaria_remPop', PACKAGE = 'cnidaria', raq, key)
}

#' Block for the next message on the redis aggregate queue
#'
#' @param raq The redis aggregate queue
#' @param timeout The number of seconds to wait for the next message
#' @return NULL if the timeout is reached otherwise the next message
#' @export
nextRAQMessage <- function(raq, timeout) {
    .Call('cnidaria_nextRAQMessage', PACKAGE = 'cnidaria', raq, timeout)
}

#' Are there any messages in the redis aggregate queue
#'
#' @param raq The redis aggregate queue
#' @return TRUE if the queue is empty FALSE otherwise
#' @export
empty <- function(raq) {
    .Call('cnidaria_empty', PACKAGE = 'cnidaria', raq)
}

makePopListener <- function(ip, port) {
    .Call('cnidaria_makePopListener', PACKAGE = 'cnidaria', ip, port)
}

add <- function(ppl, key) {
    .Call('cnidaria_add', PACKAGE = 'cnidaria', ppl, key)
}

remove <- function(ppl, key) {
    .Call('cnidaria_remove', PACKAGE = 'cnidaria', ppl, key)
}

keys <- function(ppl) {
    .Call('cnidaria_keys', PACKAGE = 'cnidaria', ppl)
}

size <- function(ppl) {
    .Call('cnidaria_size', PACKAGE = 'cnidaria', ppl)
}

nextMessage <- function(ppl) {
    .Call('cnidaria_nextMessage', PACKAGE = 'cnidaria', ppl)
}

